[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
hello_world = "6kkXgLZiDs4dTsAbc81bx9CR48A51VBVLx2Bv2usj4Wv"

[programs.devnet]
hello_world = "6kkXgLZiDs4dTsAbc81bx9CR48A51VBVLx2Bv2usj4Wv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/cmadison/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
